### ISSUE TITLE
Running example of UVM Verilator?

### ISSUE THREAD

**Issue by svenka3** [chipsalliance/uvm-verilator#4]
Is there a simple example of UVM running with Verilator? I understand there is active development and not all features work, just checking to see where we are on this very interesting development.

Thanks

**Comment by wsnyder** [comment]
UVM doesn't get past elaboration yet, so no.  If you want to see how it runs only in order to contribute (as it won't help you in any other way), see the verilator_ext_tests.

P.S. This is better discussed in the [verilator github](https://github.com/verilator/verilator) area, as it is not an issue with this repository, thanks.

**Comment by wsnyder** [comment]
P.S. This is better discussed in the verilator github area, as it is not an issue with this repository, thanks.
